language: node_js
dist: trusty
sudo: required

stages:
  - name: test
  - name: release
    if: tag = "release"

jobs:
  include:
    # In app tests
    ##############
    - stage: test
      name: unit-tests
      node_js:
        - "node"
      cache:
        directories:
          - build/src/node_modules
      install:
        # This is a dockerized application, the node app is in /build/src
        - cd ./build/src
        - npm install
      before_script:
        - npm run lint
      script:
        - npm run test

    # Test integration (in docker)
    # - Also tests the build
    ##############################
    - stage: test
      name: integration-tests
      services:
        - docker
      before_script:
        - docker build -f build/Dockerfile -t vpn.dnp.dappnode.eth:int-test-base build
      script:
        - docker build -t int-test -f tests/Dockerfile .
        - docker run int-test

    # Deploy stage
    # - code below is common between DAppNode packages
    ##################################################
    - stage: release
      name: release
      services:
        - docker
      script:
        - npm install -g @dappnode/dappnodesdk
        - docker-compose build
        - dappnodesdk publish patch -p infura
      node_js: lts/*
      before_deploy:
        - wget https://raw.githubusercontent.com/dappnode/DAppNode/master/scripts/before_deploy.sh
        - source before_deploy.sh
      deploy:
        provider: releases
        prerelease: true
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        # $RELEASE_VERSION is exported on before_deploy.sh
        file: build_${RELEASE_VERSION}/*
        skip_cleanup: true
        # $TRAVIS_TAG is exported on before_deploy.sh
        name: "$TRAVIS_TAG"
        body: "# Changelog"
        on:
          branch: master
          tags: true
          condition: "$TRAVIS_TAG =~ ^release*$"
      after_deploy:
        - wget https://raw.githubusercontent.com/dappnode/DAppNode/master/scripts/after_deploy.sh
        - source after_deploy.sh
