version: '3.4'

services:
  dnp_vpn:
    build: ./build
    image: dappnode/dnp_vpn
    container_name: dnp_vpn
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
    ports:
      - 4500:4500/udp
      - 500:500/udp
  crossbar:
    image: crossbario/crossbar
    ports:
      - 8080:8080
