version: '3.4'
networks:
    network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.33.0.0/16

volumes:
    vpndnpdappnodeeth_data: {}
    vpndnpdappnodeeth_config: {}
    vpndnpdappnodeeth_shared: {}

services:
    openvpn.dnp.dappnode.eth:
        build: ./build
        image: 'vpn.dnp.dappnode.eth:openvpn'
        container_name: DAppNodeCore-vpn.dnp.dappnode.eth
        privileged: true
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/hostname:/etc/vpnname:ro'
            - '/usr/src/dappnode/config:/usr/src/app/config:ro'
            - 'vpndnpdappnodeeth_data:/usr/src/app/secrets'
            - 'vpndnpdappnodeeth_config:/etc/openvpn'
            - 'vpndnpdappnodeeth_shared:/var/spool/openvpn'
        ports:
            - '1194:1194/udp'
        dns: 172.33.1.2
        networks:
            network:
                ipv4_address: 172.33.1.10
