version: '3.4'

services:
  dnp_vpn:
    build: ./build_vpn
    image: dappnode/dnp_vpn
    container_name: dnp_vpn
    privileged: true
    volumes:
      - etc-vpn:/etc
    ports:
      - 4500:4500/udp
      - 500:500/udp
# uncomment for testing the vpn without the rest of DAppNode
  crossbar:
    image: crossbario/crossbar
    ports:
      - 8080:8080
  dnp__vpn_mgm:
    build: ./build_usrmngmt
    container_name: dnp_vpn_mgm
    privileged: true
    volumes:
      - etc-vpn:/etc

volumes:
  etc-vpn:
