version: '3.4'

networks:
    network:
        driver: bridge

services:
  dnp_vpn:
    build: ./build_alpine
    image: dappnode/dnp_vpn
    container_name: dnp_vpn
    privileged: true
    volumes:
      - /etc/hostname:/etc/vpnname:ro
      - /lib/modules:/lib/modules:ro
    ports:
      - 4500:4500/udp
      - 500:500/udp
    networks:
            network:
