name: "Main"
on:
  pull_request:
    paths:
      - "build/**"
  push:
    branches:
      - master
    paths:
      - "build/**"

jobs:
  unit-test:
    runs-on: ubuntu-16.04
    name: Unit tests
    env:
      working-directory: ./build/src
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn install
        working-directory: ${{ env.working-directory }}
      - run: yarn lint
        working-directory: ${{ env.working-directory }}
      - run: yarn test
        working-directory: ${{ env.working-directory }}

  build-test:
    runs-on: ubuntu-16.04
    name: Build test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: docker-compose build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [unit-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    env:
      TRAVIS: yes
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install -g @dappnode/dappnodesdk
      - run: docker-compose build
      - name: Publish
        run: dappnodesdk publish patch --dappnode_team_preset --provider infura
